server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: geo
    password: 14168779
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092

jwt:
  expiration: 86400000 # 24 hours

logging:
  level:
    org.springframework.aop: DEBUG
    org.springframework.beans: DEBUG
    org.springframework.transaction: DEBUG
    root: INFO
    ru.petproject.ecommerce.user_service.security.JwtTokenProvider: DEBUG
